version: '3.3'
services:
    black_gen_ai_base:
        build: runpod
        env_file:
            - ./.env        
        container_name: black_gen_ai_base        
        ports:
            - '7860:7860'      
            - '3001:3001'      
            - '5000:5000'      
            - '8888:8888'      
            - '22:22'
        volumes:
            - ../../workspace:/workspace